export const catalogCopy = {
  ru: {
    tracks: "Атлас трасс", cars: "Гараж GT3", library: "Подготовка к заезду",
    trackIntro: "Реальные фото с разных ракурсов, схема круга и ключевые связки — подготовься к следующей сессии.",
    carIntro: "Найди свой автомобиль. Разберись в его характере и выбери направление настройки.",
    searchTracks: "Найти трассу или страну", searchCars: "Найти марку или модель",
    results: "Найдено", empty: "Ничего не найдено", emptyHint: "Попробуй другое название или сбрось поиск.", clear: "Сбросить поиск",
    all: "Все", track: "Трасса", car: "Автомобиль", length: "Длина", corners: "Повороты", sectors: "Секторы",
    layout: "Конфигурация трассы", schematic: "Схематическое изображение", explore: "Выбери сектор для изучения", fullLap: "Весь круг",
    character: "Характер трассы", sectorGuide: "Путеводитель по секторам", keyCorners: "Ключевые повороты",
    prepare: "От схемы к своему кругу", prepareHint: "Загрузи телеметрию, чтобы разобрать торможения, скорость и работу газом.",
    analyze: "Открыть телеметрию", noTiming: "Это справочник трассы. Личные результаты появятся в анализе загруженной телеметрии.",
    overview: "Характер", setup: "Основы настройки", trackSetup: "Под трассу", strengths: "Сильные стороны", attention: "Что учитывать",
    power: "Мощность", weight: "Масса", speed: "Макс. скорость", acceleration: "0–100 км/ч", hp: "л. с.", kg: "кг", kmh: "км/ч", km: "км", sec: "с",
    specNote: "Ориентировочные характеристики. Значения зависят от симулятора, настроек и баланса производительности (BoP).",
    setupNote: "Направления для тестирования, а не готовый сетап. Меняй один параметр за раз и сравнивай поведение в одинаковых условиях.",
    condition: "Условия", dry: "Сухо", wet: "Дождь", intermediate: "Переменные", focus: "Фокус настройки",
    rearDrive: "Задний привод", frontDrive: "Передний привод", allDrive: "Полный привод", illustration: "Стилизованный силуэт GT3",
    high: "Сильное влияние", medium: "Среднее влияние", low: "Небольшое влияние", selected: "Выбрано",
    easy: "Начальная", moderate: "Средняя", hard: "Высокая", expert: "Экспертная", difficulty: "Сложность",
    aero: "Аэродинамика", suspension: "Подвеска", differential: "Дифференциал", brake: "Тормоза", tyres: "Шины",
  },
  en: {
    tracks: "Circuit atlas", cars: "GT3 garage", library: "Prepare for your next stint",
    trackIntro: "Real photographs from multiple angles, the lap schematic and key sequences — prepare for your next session.",
    carIntro: "Find your car. Understand its character and choose a setup direction.",
    searchTracks: "Search circuits or countries", searchCars: "Search makes or models",
    results: "Found", empty: "No matches found", emptyHint: "Try another name or clear your search.", clear: "Clear search",
    all: "All", track: "Circuit", car: "Car", length: "Length", corners: "Corners", sectors: "Sectors",
    layout: "Circuit layout", schematic: "Schematic illustration", explore: "Select a sector to explore", fullLap: "Full lap",
    character: "Circuit character", sectorGuide: "Sector guide", keyCorners: "Key corners",
    prepare: "From the map to your own lap", prepareHint: "Upload telemetry to explore your braking, speed and throttle application.",
    analyze: "Open telemetry", noTiming: "This is a circuit guide. Personal results are available in the analysis of your uploaded telemetry.",
    overview: "Character", setup: "Setup basics", trackSetup: "Circuit setup", strengths: "Strengths", attention: "What to watch",
    power: "Power", weight: "Weight", speed: "Top speed", acceleration: "0–100 km/h", hp: "hp", kg: "kg", kmh: "km/h", km: "km", sec: "s",
    specNote: "Indicative specifications. Values depend on the simulator, setup and Balance of Performance (BoP).",
    setupNote: "Directions to test, not a ready-made setup. Change one parameter at a time and compare behaviour in the same conditions.",
    condition: "Conditions", dry: "Dry", wet: "Wet", intermediate: "Mixed", focus: "Setup focus",
    rearDrive: "Rear-wheel drive", frontDrive: "Front-wheel drive", allDrive: "All-wheel drive", illustration: "Stylised GT3 silhouette",
    high: "High impact", medium: "Medium impact", low: "Low impact", selected: "Selected",
    easy: "Beginner", moderate: "Moderate", hard: "High", expert: "Expert", difficulty: "Difficulty",
    aero: "Aerodynamics", suspension: "Suspension", differential: "Differential", brake: "Brakes", tyres: "Tyres",
  },
};
